# Generated by Django 4.0 on 2024-04-05 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circle', '0004_alter_circle_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='users',
            field=models.ManyToManyField(related_name='circles', to=settings.AUTH_USER_MODEL),
        ),
    ]
