# Generated by Django 4.0 on 2024-04-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
