# Generated by Django 4.0 on 2024-04-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
